camera0: 005
camera1: 009
frame_width: 1920
frame_height: 1200
mono_calibration_frames: 15
stereo_calibration_frames: 15
view_resize: 2
checkerboard_box_size_scale : 1.5
checkerboard_rows: 5
checkerboard_columns: 8
cooldown: 300
